'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegisterDetails

    '''<summary>
    '''formRegisterDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formRegisterDetails As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''LabelUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUsername As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelActions As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LabelYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelYear As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonUpdateYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonUpdateYear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonDeleteStudent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDeleteStudent As Global.System.Web.UI.WebControls.Button
End Class
